### ISSUE TITLE
Mean/covariance of a dataset + effect of a linear transformation (Issues with affine_mean and affine_cov)

### ISSUE THREAD

**Issue by zahrafarajih** [TheKidPadra/Mathematics_for_Machine_Learning#1]
One thing I'm wondering is do we have to always consider a random X inside the function since X is not part of the parameters. The issue is that the result of mean(X) which "mean" parameter is supposed to be equal to is tied to X. If we already have "mean(X)" as input, why do we still need to randomly create an X inside the functions, affine_mean and affine_cov.

How do we deduct X to calculate Axi+b when we just have mean(X)!

In the testing part, I have to manually consider an X that matches the mean(X) matrix given as input, otherwise it would fail. and it would be weird to always manually change X inside the function to match the mean(X) given as parameter. Having X as parameter would seemingly be a good option.

So my question is, how to create an X inside the function that matches every mean(X) given as input? or Can I just alter the function and put X as one of the parameters?

**Comment by TheKidPadra** [comment]
What I did for these exercises was I used the two formulas: E(AX+b) = A*E(X) + b and Cov(AX+B) = A*Cov(X)*A.T to calculate the mean and covariance matrix of X after linear transformation. 
try this one

**Comment by zahrafarajih** [comment]
I completely lost sight of how E(AX+b) and E(X) were related to each other, as well as Cov(AX+b) and Cov(X). I was focused on calculating AX+b within my functions, and that required me to have some X to apply the linear transformation on. 
thank you very much
